# name: Todoist Readme

# on:
#   workflow_dispatch:
#   schedule:
#     # Runs every minute
#     - cron: "0 */6 * * *"

# jobs:
#   update-readme:
#     name: Update todoist stats
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: abhisheknaiidu/todoist-readme@master
#         with:
#           TODOIST_API_KEY: ${{ secrets.TODOIST }}
#           PREMIUM: ""
