name: Waka Readme

on:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "id"
          SHOW_OS: "True"
          SHOW_PROJECTS: "False"         # ⛔ jangan tampilkan project
          SHOW_LINES_OF_CODE: "False"    # ⛔ jangan tampilkan LOC graph
          SHOW_TOTAL_CODE_TIME: "False"  # ⛔ jangan tampilkan total sepanjang waktu
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "False"
          COMMIT_MESSAGE: "Updated with minimal dev metrics"
          COMMIT_USERNAME: "readme-bot"
